"""add mental health logs table and origin story field

Revision ID: 2eb945710b88
Revises: 365286d11b3b
Create Date: 2026-05-13 09:56:47.354325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb945710b88'
down_revision: Union[str, None] = '365286d11b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mental_health_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.Enum('individual', 'group', 'emergency', 'follow_up', name='sessiontype'), nullable=False),
    sa.Column('wellbeing_rating', sa.Integer(), nullable=True),
    sa.Column('session_notes', sa.Text(), nullable=True),
    sa.Column('trauma_milestone', sa.String(length=500), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('next_session_date', sa.Date(), nullable=True),
    sa.Column('counselor_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['counselor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mental_health_logs_child_id'), 'mental_health_logs', ['child_id'], unique=False)
    op.create_index(op.f('ix_mental_health_logs_session_date'), 'mental_health_logs', ['session_date'], unique=False)
    op.add_column('children', sa.Column('origin_story', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children', 'origin_story')
    op.drop_index(op.f('ix_mental_health_logs_session_date'), table_name='mental_health_logs')
    op.drop_index(op.f('ix_mental_health_logs_child_id'), table_name='mental_health_logs')
    op.drop_table('mental_health_logs')
    # ### end Alembic commands ###
