"""add biometric records table

Revision ID: 365286d11b3b
Revises: d6a0487355c0
Create Date: 2026-05-12 22:12:40.613973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365286d11b3b'
down_revision: Union[str, None] = 'd6a0487355c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biometric_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('allergies', sa.String(length=500), nullable=True),
    sa.Column('blood_type', sa.String(length=10), nullable=True),
    sa.Column('health_notes', sa.Text(), nullable=True),
    sa.Column('next_checkup_date', sa.Date(), nullable=True),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometric_records_child_id'), 'biometric_records', ['child_id'], unique=False)
    op.create_index(op.f('ix_biometric_records_record_date'), 'biometric_records', ['record_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biometric_records_record_date'), table_name='biometric_records')
    op.drop_index(op.f('ix_biometric_records_child_id'), table_name='biometric_records')
    op.drop_table('biometric_records')
    # ### end Alembic commands ###
