"""add activities and meals tables

Revision ID: d6a0487355c0
Revises: 297cffdbf041
Create Date: 2026-05-12 10:49:12.926151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a0487355c0'
down_revision: Union[str, None] = '297cffdbf041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('activity_type', sa.Enum('football', 'dance', 'choir', 'drama', 'basketball', 'volleyball', 'athletics', 'vocational_tailoring', 'vocational_carpentry', 'vocational_cooking', 'vocational_computing', 'other', name='activitytype'), nullable=False),
    sa.Column('activity_name', sa.String(length=200), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('participation_level', sa.Enum('observer', 'active', 'leader', name='participationlevel'), nullable=False),
    sa.Column('instructor_notes', sa.Text(), nullable=True),
    sa.Column('vocational_status', sa.Enum('in_progress', 'certified', 'did_not_complete', name='vocationalstatus'), nullable=True),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_date'), 'activities', ['activity_date'], unique=False)
    op.create_index(op.f('ix_activities_child_id'), 'activities', ['child_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='mealtype'), nullable=False),
    sa.Column('served', sa.Boolean(), nullable=False),
    sa.Column('quantity_notes', sa.String(length=200), nullable=True),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_child_id'), 'meals', ['child_id'], unique=False)
    op.create_index(op.f('ix_meals_meal_date'), 'meals', ['meal_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meals_meal_date'), table_name='meals')
    op.drop_index(op.f('ix_meals_child_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_activities_child_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_date'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
