"""add grades table

Revision ID: fa4801c4704d
Revises: 34d83fdedf81
Create Date: 2026-05-05 19:50:34.846618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4801c4704d'
down_revision: Union[str, None] = '34d83fdedf81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('term', sa.Enum('term_1', 'term_2', 'term_3', name='term'), nullable=False),
    sa.Column('academic_year', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_child_id'), 'grades', ['child_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grades_child_id'), table_name='grades')
    op.drop_table('grades')
    # ### end Alembic commands ###
